# Generated by Django 5.0.7 on 2024-07-29 15:24

from django.db import migrations
from django.contrib.auth.hashers import make_password


class Migration(migrations.Migration):

    def create_superuser(apps, schema_editor):
        ApplicationUser = apps.get_model('users', 'ApplicationUser')

        user = ApplicationUser.objects.create(
            email='root@example.com',
            password=make_password('P@ssword123'),
            first_name='Root',
            last_name='User',
            is_superuser=True,
            is_staff=True
        )
        user.save()

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
