# Generated by Django 5.0.7 on 2024-07-29 15:11

from django.db import migrations


def create_permissions(apps, schema_editor):
    Permission = apps.get_model('permissions', 'Permission')

    permissions = [
        ('CanLogin', 'Can login to the system'),
        ('MustChangePassword', 'Must change password on first login'),
        ('CanCreateUser', 'Can create a new user'),
        ('CanEditUser', 'Can edit user details'),
        ('CanDeleteUser', 'Can delete a user'),
        ('CanViewUser', 'Can view user details'),
        ('CanCreateRole', 'Can create a new role'),
        ('CanEditRole', 'Can edit role details'),
        ('CanDeleteRole', 'Can delete a role'),
        ('CanViewRole', 'Can view role details'),
        ('Administrator', 'Can perform any action on the system'),
    ]

    for name, desc in permissions:
        permission = Permission.objects.create(name=name, description=desc)
        permission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_permissions)
    ]
